# Generated by Django 4.0.4 on 2022-05-26 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('like', models.IntegerField(default='0')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_post', to='category.category')),
            ],
        ),
    ]
